import { JourneyItem } from "@/types/portfolio";

export const journeyData: JourneyItem[] = [
  {
    id: "j-1",
    title: "Class 10 — D.A.V High School, Jharia",
    subtitle: "CBSE Board Examination — 80%",
    date: "2020",
    description: "Completed Class 10 CBSE Board Examination at D.A.V High School, Jharia with 80%.",
    category: "Education",
    order: 1,
  },
  {
    id: "j-2",
    title: "Diploma in Engineering",
    subtitle: "Government Polytechnic Jagannathpur",
    date: "2020–2023",
    description: "Completed Diploma in Engineering at Government Polytechnic Jagannathpur, West Singhbhum, Jharkhand with 67.69%.",
    category: "Education",
    order: 2,
  },
  {
    id: "j-3",
    title: "B.Tech in Computer Science",
    subtitle: "GITA University, Bhubaneswar",
    date: "2024–2027",
    description: "Enrolled in B.Tech Computer Science at GITA University, Bhubaneswar via Lateral Entry.",
    category: "Education",
    order: 3,
  },
  {
    id: "j-4",
    title: "Machine Learning / Computer Vision Projects",
    subtitle: "AI/ML Development & OpenCV",
    date: "2025+",
    description: "Built practical machine learning and computer vision systems including Face Mask Detection, Fake AI Image Detector, and Phishing Website Detection.",
    category: "AI/ML",
    order: 4,
    relatedProjectSlug: "fake-ai-image-detector",
  },
  {
    id: "j-5",
    title: "Full-Stack Development & Internships",
    subtitle: "Django, React, Next.js & OCAC Internship",
    date: "2025–2026",
    description: "Developed full-stack web applications including Real-Time Social Media Platform, AI Interview Coach, and Personal Portfolio during 12-month OCAC internship.",
    category: "Full Stack",
    order: 5,
    relatedProjectSlug: "ai-interview-coach",
  },
  {
    id: "j-6",
    title: "Explainable Machine Learning Research",
    subtitle: "Phishing Website Detection & Intended IEEE Publication",
    date: "2026",
    description: "Conducted research on URL-based phishing website detection using 9 ML classifiers, Information Gain feature selection, Optuna tuning, and SHAP explainability.",
    category: "Research",
    order: 6,
    relatedResearchSlug: "explainable-phishing-detection-research",
  },
];
