import { Skill } from "@/types/portfolio";

export const skillsData: Skill[] = [
  {
    name: "Programming Languages",
    slug: "programming-languages",
    category: "Languages",
    description: "Core programming languages used for software development, systems engineering, and machine learning.",
    featured: true,
    order: 1,
    active: true,
    technologies: ["Python", "C", "C++", "JavaScript"],
  },
  {
    name: "Frontend Development",
    slug: "frontend-development",
    category: "Frontend",
    description: "Building responsive web interfaces and user components.",
    featured: true,
    order: 2,
    active: true,
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Backend Frameworks & Real-Time APIs",
    slug: "backend-frameworks",
    category: "Backend",
    description: "Developing RESTful APIs, web applications, and real-time WebSocket communication backends.",
    featured: true,
    order: 3,
    active: true,
    technologies: ["Django", "Django REST Framework", "Django Channels"],
  },
  {
    name: "Databases & In-Memory Stores",
    slug: "databases",
    category: "Database",
    description: "Managing relational databases and caching layers for web and ML applications.",
    featured: true,
    order: 4,
    active: true,
    technologies: ["PostgreSQL", "MySQL", "Redis"],
  },
  {
    name: "AI & Machine Learning Frameworks",
    slug: "ai-machine-learning",
    category: "AI/ML",
    description: "Building machine learning models, computer vision pipelines, and deep learning architectures.",
    featured: true,
    order: 5,
    active: true,
    technologies: ["TensorFlow", "Keras", "OpenCV", "XGBoost", "LightGBM", "CatBoost", "Scikit-learn"],
  },
  {
    name: "ML Explainability & Optimization",
    slug: "ml-explainability-research",
    category: "ML/Research",
    description: "Model interpretability, hyperparameter tuning, feature selection, and explainable AI techniques.",
    featured: true,
    order: 6,
    active: true,
    technologies: ["SHAP", "Optuna", "RandomizedSearchCV", "Feature Selection", "Explainable AI"],
  },
  {
    name: "Developer Tools & Media Utilities",
    slug: "developer-tools",
    category: "Tools",
    description: "Development environments, version control, and multimedia processing libraries.",
    featured: true,
    order: 7,
    active: true,
    technologies: ["Git", "GitHub", "VS Code", "Anaconda", "FFmpeg"],
  },
  {
    name: "Deployment & Cloud Hosting",
    slug: "deployment-hosting",
    category: "Deployment",
    description: "Deploying production web applications and APIs to serverless and managed cloud platforms.",
    featured: true,
    order: 8,
    active: true,
    technologies: ["Vercel", "Render"],
  },
];
